config/routes.rb
Rails.application.routes.draw do
  root "weeks#index"
  resources :weeks
  resources :codes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/code.rb
class Code < ApplicationRecord
  belongs_to :week
end

app/models/week.rb
class Week < ApplicationRecord
  has_many :codes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: %i[show edit update destroy]
  http_basic_authenticate_with name: 'admin', password: 'beleriand.justdied', except: %i[index show]

  def index
    @codes = Code.all
  end

  def show; end

  def new
    @code = Code.new
  end

  def edit; end

  def create
    @code = Code.new(code_params)

    if @code.save
      redirect_to code_url(@code), notice: 'Code was successfully created.'
    else
       render :new, status: :unprocessable_entity
    end
  end

  def update
    if @code.update(code_params)
      redirect_to code_url(@code), notice: 'Code was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @code.destroy

    redirect_to codes_url, notice: 'Code was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_code
    @code = Code.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def code_params
    params.require(:code).permit(:description, :code_text, :week_id)
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :set_week, only: %i[show edit update destroy]
  http_basic_authenticate_with name: 'admin', password: 'beleriand.justdied', except: %i[index show]

  # GET /weeks or /weeks.json
  def index
    @weeks = Week.all.order(created_at: :desc)
    @mates = [
      { name: 'Alex', colors: 'white' },
      { name: 'Bruna', colors: 'black' },
      { name: 'Camilla', colors: %w[limegreen dodgerblue] },
      { name: 'Daniel', colors: 'green' },
      { name: 'Guilherme', colors: 'red' },
      { name: 'João', colors: 'orange' },
      { name: 'Natã', colors: 'rebeccapurple' },
      { name: 'Victor', colors: 'yellow' }
    ]
  end

  # GET /weeks/1 or /weeks/1.json
  def show; end

  # GET /weeks/new
  def new
    @week = Week.new
  end

  # GET /weeks/1/edit
  def edit; end

  # POST /weeks or /weeks.json
  def create
    @week = Week.new(week_params)

    respond_to do |format|
      if @week.save
        format.html { redirect_to week_url(@week), notice: 'Week was successfully created.' }
        format.json { render :show, status: :created, location: @week }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weeks/1 or /weeks/1.json
  def update
    respond_to do |format|
      if @week.update(week_params)
        format.html { redirect_to week_url(@week), notice: 'Week was successfully updated.' }
        format.json { render :show, status: :ok, location: @week }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1 or /weeks/1.json
  def destroy
    @week.destroy

    respond_to do |format|
      format.html { redirect_to weeks_url, notice: 'Week was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_week
    @week = Week.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def week_params
    params.require(:week).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/codes/_code.html.erb
<div id="<%= dom_id code %>">
  <p>
    <strong>Description:</strong>
    <%= code.description %>
  </p>

  <p>
    <strong>Code text:</strong>
    <%= code.code_text %>
  </p>

</div>

app/views/codes/_form.html.erb
<%= form_with(model: code) do |form| %>
  <% if code.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
        <% code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :code_text, style: "display: block" %>
    <%= form.text_area :code_text %>
  </div>

  <div>
    <%= form.label :week_id, style: "display: block" %>
    <%= form.number_field :week_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing code</h1>

<%= render "form", code: @code %>

<br>

<div>
  <%= link_to "Show this code", @code %> |
  <%= link_to "Back to codes", codes_path %>
</div>

app/views/codes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lista de Exercícios</h1>

<div id="codes">
  <% @codes.each do |code| %>
    <span><%= code.description %></span>
    <p>
      <%= link_to "Resposta", code %>
    </p>
    <hr>
  <% end %>
</div>

app/views/codes/new.html.erb
<h1>New code</h1>

<%= render "form", code: @code %>

<br>

<div>
  <%= link_to "Back to codes", codes_path %>
</div>

app/views/codes/show.html.erb
<style>
  .wrapper {
    display: flex;
    align-items: center;
  } 
  .wrapper h4 {
    margin-right: 2%;
  }
  .wrapper button  {
    background-color: var(--accent);
    height: 40%;
  }
 </style>
<p style="color: green"><%= notice %></p>
<div class="wrapper">
  <h4><%= @code.description %></h4>
  <button onclick="copyText(c<%= @code.id %>)">
    <svg style="width: 25px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
      <path d="M384 96L384 0h-112c-26.51 0-48 21.49-48 48v288c0 26.51 21.49 48 48 48H464c26.51 0 48-21.49 48-48V128h-95.1C398.4 128 384 113.6 384 96zM416 0v96h96L416 0zM192 352V128h-144c-26.51 0-48 21.49-48 48v288c0 26.51 21.49 48 48 48h192c26.51 0 48-21.49 48-48L288 416h-32C220.7 416 192 387.3 192 352z"/>
    </svg>
  </button>
</div>
<pre><code class="language-bash" id="c<%= @code.id %>"><%= @code.code_text %></code></pre>
<div>
  <%= link_to :back do %>
    <button>Voltar</button>
  <% end %>
</div>


<script>
  function copyText(id) {
    let text = id.innerText
    navigator.clipboard.writeText(text);
  }
</script>

<script>hljs.highlightAll();</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  <!-- Primary Meta Tags -->
    <title>Exercícios do Frederico</title>
    <meta name="title" content="TCP's Code Viewer :)">
    <meta name="description" content="Método diferenciado de se compartilhar código :D">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.min.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://unpkg.com/@highlightjs/cdn-assets@11.5.1/styles/tokyo-night-dark.min.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "//unpkg.com/@highlightjs/cdn-assets@11.5.1/highlight.min.js" %>
    <%= javascript_tag "hljs.highlightAll();" %>
  </head>

  <body>
    <nav style="display: flex; justify-content: space-around">
      <%= link_to 'Home', root_path %>
      <%= link_to 'Todos os Exercícios', codes_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/weeks/_form.html.erb
<%= form_with(model: week) do |form| %>
  <% if week.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(week.errors.count, "error") %> prohibited this week from being saved:</h2>

      <ul>
        <% week.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weeks/_hearts.html.erb
<% @hearticon = capture do %>
  <path d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z"/>
<% end %>

<span class="footer-span">
  <%= mate[:name] %>
  <% if mate[:colors].is_a? Array %>
    <% mate[:colors].each do |color| %>
      <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="width: 1rem;fill: <%= color %>;" ><%= @hearticon %></svg></span>
    <% end %>

  <% else %>
    <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="width: 1rem;fill: <%= mate[:colors] %>;" ><%= @hearticon %></svg></span>
  <% end %>
</span>

app/views/weeks/_week.html.erb
<div id="<%= dom_id week %>">
  <p>
    <strong>Title:</strong>
    <%= week.title %>
  </p>

</div>

app/views/weeks/edit.html.erb
<h1>Editing week</h1>

<%= render "form", week: @week %>

<br>

<div>
  <%= link_to "Show this week", @week %> |
  <%= link_to "Back to weeks", weeks_path %>
</div>

app/views/weeks/index.html.erb
<p style="color: green"><%= notice %></p>

<h3>Clique em uma data e veja o que acontece</h3>
<div id="weeks">
  <% @weeks.each do |week| %>
    <%= link_to week do %>
      <hr>
      <h2><%= week.title %></h2>
    <% end %>
  <% end %>
</div>

<footer>
   <p>Esse site foi feito para ajudar na hora de mandar cola- qu-quer dizer... códigos para outras pessoas, sem que seja necessário copiar e mandar várias vezes.</p> 
   <p>Qualquer bug, erro, ou algo fora do comum por favor me avise :D</p> 

   <p><%= render 'hearts', mate: @mates.sample %></p>
 </footer>

app/views/weeks/new.html.erb
<h1>New week</h1>

<%= render "form", week: @week %>

<br>

<div>
  <%= link_to "Back to weeks", weeks_path %>
</div>

app/views/weeks/show.html.erb
<p style="color: green"><%= notice %></p>

<h3>Exercícios do dia <%= @week.title %></h3>
<div id="codes">
  <% @week.codes.each do |code| %>
      <span><%= code.description %></span>
      <p>
        <%= link_to "Resposta", code %>
      </p>
      <hr>
  <% end %>
</div>